# Form implementation generated from reading ui file 'FuncWind.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FuncWind(object):
    def setupUi(self, FuncWind):
        FuncWind.setObjectName("FuncWind")
        FuncWind.resize(1080, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo_vert.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FuncWind.setWindowIcon(icon)
        FuncWind.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: #fff;\n"
"    padding: 14px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 12px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3e8e41\n"
"}")
        self.centralwidget = QtWidgets.QWidget(FuncWind)
        self.centralwidget.setObjectName("centralwidget")
        self.AddNoteTable = QtWidgets.QTableView(self.centralwidget)
        self.AddNoteTable.setGeometry(QtCore.QRect(20, 10, 1041, 411))
        self.AddNoteTable.setObjectName("AddNoteTable")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 1051, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoadNote = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.LoadNote.setFont(font)
        self.LoadNote.setObjectName("LoadNote")
        self.horizontalLayout.addWidget(self.LoadNote)
        self.EditNote = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.EditNote.setFont(font)
        self.EditNote.setObjectName("EditNote")
        self.horizontalLayout.addWidget(self.EditNote)
        self.DeleteNote = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.DeleteNote.setFont(font)
        self.DeleteNote.setObjectName("DeleteNote")
        self.horizontalLayout.addWidget(self.DeleteNote)
        FuncWind.setCentralWidget(self.centralwidget)

        self.retranslateUi(FuncWind)
        QtCore.QMetaObject.connectSlotsByName(FuncWind)

    def retranslateUi(self, FuncWind):
        _translate = QtCore.QCoreApplication.translate
        FuncWind.setWindowTitle(_translate("FuncWind", "Работа с данными"))
        self.LoadNote.setText(_translate("FuncWind", "Загрузить данные"))
        self.EditNote.setText(_translate("FuncWind", "Изменить данные"))
        self.DeleteNote.setText(_translate("FuncWind", "Удалить данные"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FuncWind = QtWidgets.QMainWindow()
    ui = Ui_FuncWind()
    ui.setupUi(FuncWind)
    FuncWind.show()
    sys.exit(app.exec())
